services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - local
  
  application:
    image: application
    build:
      context: .
      dockerfile: Application/Dockerfile

networks:
  local:
    driver: bridge